version: "3"

services:
  expense-manager-api:
    container_name: expense-manager-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=expense-manager-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD:root
      - HIKARI_POOL_SIZE=2
      - JTW_SECRET=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength

  mysql:
    image: mysql
    container_name: expense-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
