version: "3"

services:
  mysql:
    image: mysql
    container_name: expense-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
