spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
    username: root
    password: root

jwt:
  expiration: 60000
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
